/cf1:
  platform:
    ros__parameters:
      uri: radio://0/33/2M/E7E7E7AAAC
      cam_ip: "192.168.4.1" 
      cam_port: 5000 

# /cf2:
#   platform:
#     ros__parameters:
#       uri: radio://0/80/2M/E7E7E7E700
#       cam_ip: "192.168.4.1"
#       cam_port: 5000 
      
# /cf3:
#   platform:
#     ros__parameters:
#       uri: radio://0/80/2M/E7E7E7E701
#       cam_ip: "192.168.4.1"
#       cam_port: 5000 


